name: publish_to_brickyard

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: publish_codepad
        uses: abitofevrything/publish-mason-brick@1.0.4
        with:
          path: codepad
          email: ${{ secrets.BRICKHUB_EMAIL }}
          password: ${{ secrets.BRICKHUB_PASSWORD }}
