name: publish_to_brickyard

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install Mason
        run: dart pub global activate mason_cli

      - name: Log in to BrickHub
        run: mason login --email ${{ secrets.BRICKHUB_EMAIL }} --password ${{ secrets.BRICKHUB_PASSWORD }}

      - name: Publish codepad
        run: mason publish --directory codepad --force