name: publish_to_brickyard

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install Mason
        run: dart pub global activate mason_cli

      - name: Create credentials file
        run: |
          mkdir -p ~/.config/mason
          echo '${{ secrets.MASON_CREDENTIALS }}' > ~/.config/mason/mason-credentials.json

      - name: Publish codepad
        run: mason publish --directory codepad --force
